name: C/C++ CI com CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar CMake
      run: cmake -B build

    - name: Compilar
      run: cmake --build build
